title: Dada's Site
description: Dada public website
theme: just-the-docs

url: https:/andreadada.github.io/wiki

aux_links:
  Template Repository: https://github.com/andreadada.github.io/wiki
plugins:
  - jekyll-default-layout

defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

nav_enabled: true