title: Dada's Site
description: Dada public website
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.10.0

url: https:/andreadada.github.io

aux_links:
  Template Repository: https://github.com/andreadada.github.io

defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

nav_enabled: true


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red