title: Dada's Site
description: Dada public website
theme: just-the-docs

url: https:/andreadada.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

nav_enabled: true